version: '3'
services:

  hello_api:
    build: .
    ports:
      - 9999:8000
    volumes:
      - .:/home/node/brick
    environment:
      - BRICK_NAME=hello 
    depends_on:
      - hello_mongo
    
  hello_mongo:
    image: mongo:3.0-wheezy
    ports:
      - 27017
    volumes:
       - ./database:/data/db
